---
title: "R Notebook"
output:
  word_document: default
  html_notebook: default
---



```{r}
#Time to try a different approach to pseudotime. It's clear the way it seems to be heading is clusters 2, 1, 3, 0. 

#using this tutorial: https://rnabioco.github.io/cellar/5_trajectories.html

#make new seurat object:
#working directory, change if using on system other than authors to folder with.rds file in. 
setwd("~/OneDrive - Queen Mary, University of London/QMUL/Lab/Coding/data/R/Seurat/SandLKerato")



#load all libraries. 
library(Seurat)
library(tidyverse)
library(ggplot2)
library(DEGreport)
library(Matrix)
library(slingshot)
library(tradeSeq)
library(SingleCellExperiment)
library(RColorBrewer)
library(gam)
library(cowplot)
library(scales)
library(gridExtra)
library(destiny)
library(ComplexHeatmap)
theme_set(theme_cowplot())
library(scCustomize)


#Load in .rds object containing filtered and clustered data.
kerato <- readRDS(file = "smalllargekera.rds")

# sets colours for clusters
plot.colours <- c("#f87269","#80b00e","#00bdc2","#c679ff")
```

```{r}
#seurat object already created, but need to run PCA reduction:

newpseudokerato <- RunPCA(kerato, verbose = FALSE)

DimPlot(newpseudokerato, reduction = "umap", label = TRUE, pt.size = 0.5) + ggtitle('Clusters') +
  xlab('UMAP 1') + 
  ylab('UMAP 2') + 
  theme(plot.title = element_text(hjust = 0.5)) #centre title

# plot the PCA reduction
DimPlot(newpseudokerato, reduction = "pca")
```

```{r}
# get the PC1 values for each cell, and store in a data frame
plt_dat <- FetchData(newpseudokerato, c("PC_1", "seurat_clusters"))

# reorder cell_type based on known developmental time
cell_type <- factor(plt_dat$seurat_clusters,
                    levels = c("2",
                               "1",
                               "3",
                               "0"))

# add the reordered cell_type info as a new column to plt_data
plt_dat$cell_type <- cell_type

# plot the cells ordered by pseudotime (PC1)
ggplot(plt_dat, aes(cell_type, PC_1)) +
  geom_jitter(aes(color = seurat_clusters)) +
  labs(y = "PC1 (aka pseudotime)", x= 'Cluster') +
  ggtitle("Cells ordered by PC1") + theme(legend.position="none")
```
```{r}
# get PC1 values and rank to generate a 'pseudotime'
ptime <- FetchData(newpseudokerato, "PC_1")
ptime$ptime <- rank(ptime$PC_1)


# add pseudotime to the metadata
newpseudokerato <- AddMetaData(newpseudokerato, 
                    ptime$ptime, 
                    col.name = "Pseudotime_manual")

#save new pseudo as a .rds file
saveRDS(newpseudokerato, file = "newpseudokera.rds")
```

```{r}
#reset working directory
setwd("~/OneDrive - Queen Mary, University of London/QMUL/Lab/Coding/data/R/Seurat/SandLKerato")

#load in new newpseudokerato from .rds file
newpseudokerato <- readRDS(file = "newpseudokera.rds")
```


```{r}
#plots 
#plot showing pseudotime over clusters
FeaturePlot(newpseudokerato, features = ('Pseudotime_manual')) + xlab('UMAP 1') +
  ylab('UMAP 2') + ggtitle('PC1-based Pseudotime')

#plot for n_count RNA over pseudo
newpseudokerato %>%
  tidyseurat::ggplot(aes(x=Pseudotime_manual, y=nCount_RNA)) + 
  geom_point() + 
  stat_smooth(method="lm", se=TRUE, colour = 'black', plot.cor = TRUE) + 
  # geom_cor(method = "pearson") + 
  xlab('PC1 Pseudotime Value') +
  ylab('RNA Read Count')

#plot for % mitochondrial RNA over pseudo
newpseudokerato %>%
  tidyseurat::ggplot(aes(x=Pseudotime_manual, y=percent.mt)) +   geom_point() + 
  stat_smooth(method="lm", se=TRUE, colour = 'black', plot.cor = TRUE) + 
  # geom_cor(method = "pearson") + 
  xlab('PC1 Pseudotime Value') +
  ylab('Percentage mitochondrial content')

#plot for n_feature RNA over pseudo
newpseudokerato %>%
  tidyseurat::ggplot(aes(x=Pseudotime_manual, y=nFeature_RNA)) + 
  geom_point() + 
  stat_smooth(method="lm", se=TRUE, colour = 'black', plot.cor = TRUE) + 
  # geom_cor(method = "pearson") + 
  xlab('PC1 Pseudotime Value') +
  ylab('RNA Feature Count')
```
```{r}
#reset working directory
setwd("~/OneDrive - Queen Mary, University of London/QMUL/Lab/Coding/data/R/Seurat/SandLKerato")

#load in new newpseudokerato from .rds file
newpseudokerato <- readRDS(file = "newpseudokera.rds")
```

```{r}
# this section builds lists containing gene IDs. These IDs are sorted into lists related to their function and/or their research area associated with them. 

# kerato_marker_genes contain general keratinocyte differentiation markers.
kerato_marker_genes <- c("Krt10", "Krt5", "Krt14", "Sprr1a", "Sprr1b", "Evpl", "Dsp", "Ppl", "Klk11", "Spink5", "Klf4", "Klk6", "Klk7", "Klk8", "Klk10")

# Marker genes from:
#   https://www.researchgate.net/figure/Protein-expression-patterns-in-different-epidermal-layers-of-genes-categorized-as-skin_fig3_268792873
# https://www.google.com/imgres?imgurl=https%3A%2F%2Fmedia.springernature.com%2Ffull%2Fspringer-static%2Fimage%2Fart%253A10.1038%252Fs41467-020-18075-7%2FMediaObjects%2F41467_2020_18075_Fig1_HTML.png&imgrefurl=https%3A%2F%2Fwww.nature.com%2Farticles%2Fs41467-020-18075-7&tbnid=q0EUHPEmzdCCqM&vet=12ahUKEwjrmPGdmeL6AhUI-YUKHTMyAQYQMygAegUIARC6AQ..i&docid=M_1IAh4jlcnxFM&w=1956&h=1342&q=epidermis%20marker%20genes&ved=2ahUKEwjrmPGdmeL6AhUI-YUKHTMyAQYQMygAegUIARC6AQ



# cell_state_markers contains genes used to mark the cell cycle state of cells, in this case currently proliferative markers. 
cell_state_markers <- c("Mki67","Pcna")

# actin_markers contains all genes associated with the actin cytoskeleton. 
actin_markers <- c("Arhgdia","Camsap2", "Anxa1", "Rflnb", "Tmsb4x", "Arpc1b", "Sbsn","Dsg3", "Ahnak", "Cdh1", "Col3a1", "Tpt1", "Lgals7", "Rack1", "S100a11", "Eef1b2", "Ran", "Sprr1a", "Klf8", "Ptprf")

actin_GO_markers <- c("Anxa1", "Sptbn2", "Rflnb", "Cavin3", "Tmsb4x", "Phpt1", "Cav1", "Ctsl", "Amotl2", "Hsp90b1", "Slc2a1", "Gmfg", "Dstn", 'Arhgdia')

# plmn_markers has putative lamin bodies markers investigated. 
plmn_markers <- c("Ipo7", "Ran", "Snupn", "Matr3", "Nup153")

# SGPB_markers contains genes associated with condensates, primarly stress granules and P bodies.
SGPB_markers <- c("Ddx6", "Eif4e", "Nxf1", "Lsm14a", "Caprin1", "Csde1", "Pum1", "Zfp36")

# other_markers contains miscellaneous markers, notes below variable show reasoning. 
other_markers <- c("Snhg11", "Fabp5", "Slc25a4", "Lgals7", "Tacstd2", "Fosb", "Cd44", "Trpv4", "Trpm4" )

JAKSTATmarkers <- c("Jak1", "Jak2", "Jak3", "Stat2","Stat3","Stat4","Stat6")

Request1 <- c("Pigu", "Ggnbp2", "Notch1", "Cav1", "Hsp90b1", "Akr1b1", "Adipor1")

Request2 <- c("Id1","Bmp2")
# request 2 not found: "Dlx3", "Msx2", "Bmp6", "Grem1"

list_of_features <- c(kerato_marker_genes, cell_state_markers, actin_markers, plmn_markers, SGPB_markers, other_markers)
```

```{r}
#gene of interest plots
#gene of interest
pseudotime_scatter_gene <- 'Sptbn2'

#pseudotime graphs
FeatureScatter(newpseudokerato, feature1 = "Pseudotime_manual", feature2 = (pseudotime_scatter_gene)) +
  scale_x_reverse() +
  theme(plot.title = element_text(hjust = 1.2, vjust = -2)) + # adjust pearsons coefficient to right hand side
  stat_smooth(method="lm", se=TRUE, colour = 'black') + # regression line
    #labels
  xlab('PC1-based Pseudotime') + 
  ylab(sprintf('%s Log2 Expression', pseudotime_scatter_gene)) +
  labs(fill = "Cluster") 

#cluster graph
FeaturePlot(newpseudokerato, features = (pseudotime_scatter_gene)) + xlab('UMAP 1') +
  ylab('UMAP 2') +
  scale_color_gradientn(colors=c("black","purple","yellow"))
```
```{r}
#set what batch of genes being turned to images:
images_gene_list <- Request2
```


```{r}
setwd("~/OneDrive - Queen Mary, University of London/QMUL/Lab/Coding/data/R/Seurat/SandLKerato/images")

for (gene in images_gene_list){
  #create cluster map
  p <- FeaturePlot(newpseudokerato, features = (gene)) + xlab('UMAP 1') +
  ylab('UMAP 2')
  #print plot to console
  print(p)
  
  #this saves as a .png in the images folder with default settings.
  ggsave(filename = (sprintf('%s cluster', gene)), plot = p, device = 'png')
}
```

```{r}
# chunk plotting all pseudotime line graphs for genes in a character vector
setwd("~/OneDrive - Queen Mary, University of London/QMUL/Lab/Coding/data/R/Seurat/SandLKerato/images")

for (gene in images_gene_list){

  #build initial feature scatter plot
  p <- FeatureScatter(newpseudokerato, feature1 = "Pseudotime_manual", feature2 = (gene))
  #add overlays
  p <- p + theme(plot.title = element_text(hjust = 1.2, vjust = -2)) + # adjust pearsons coefficient to right hand side
  stat_smooth(method="lm", se=TRUE, colour = 'black') + # regression line
  scale_x_reverse() +
   #labels
  xlab('PC1-based Pseudotime') +
  ylab(sprintf('%s Log2 Expression', gene)) +
  labs(fill = "Cluster")
  #print whole plot 'p'
  print(p)
  
  #this saves as a .png in the images folder with default settings.
  ggsave(filename = (sprintf('%s line', gene)), plot = p, device = 'png')
}
```

```{r}
metadataframe <- newpseudokerato@meta.data
                                                          
grouped_qcs <- metadataframe %>% group_by(seurat_clusters) 

summary(newpseudokerato@meta.data)

grouped_qcs %>% summarise(
  mito = mean(percent.mt),
  counts = mean(nCount_RNA),
  features = mean(nFeature_RNA)
)
   
grouped_qcs %>% summarise(
  mito = median(percent.mt),
  counts = median(nCount_RNA),
  features = median(nFeature_RNA)
)

grouped_qcs %>% summarise(
  mito = min(percent.mt),
  counts = min(nCount_RNA),
  features = min(nFeature_RNA)
)   

grouped_qcs %>% summarise(
  mito = max(percent.mt),
  counts = max(nCount_RNA),
  features = max(nFeature_RNA)
)            

grouped_qcs %>% summarise(
  mito = quantile(percent.mt),
  counts = quantile(nCount_RNA),
  features = quantile(nFeature_RNA)
)                          
```


```{r}
Stacked_VlnPlot(seurat_object = newpseudokerato, features = c("Tmsb4x","Sptbn2"), x_lab_rotate = TRUE, colors_use = plot.colours) 



```

