---
title: "R Notebook"
output:
  word_document: default
  html_notebook: default
---

```{r}
# Functions and information taken from these two sources. 
## https://scrnaseq-course.cog.sanger.ac.uk/website/biological-analysis.html#pseudotime-analysis
# https://stemangiola.github.io/tidyseurat/


#Load in .rds object containing filtered and clustered data.
kerato <- readRDS(file = "pseudoSLkera.rds")

#load all libraries. 
library(dplyr)
library(Seurat)
library(patchwork)
library(data.table)
library(stringr)
library(ggplot2)
library(Signac)
library(SeuratWrappers)
library(monocle3)
library(Matrix)
library(tidyseurat)
library(DEGreport)
set.seed(1234)

#working directory, change if using on system other than authors to folder with.rds file in. 
setwd("~/OneDrive - Queen Mary, University of London/QMUL/Lab/Coding/data/R/Seurat/SandLKerato")

```


```{r}
# this section builds lists containing gene IDs. These IDs are sorted into lists related to their function and/or their research area associated with them. 

# kerato_marker_genes contain general keratinocyte differentiation markers.
kerato_marker_genes <- c("Krt10", "Krt5", "Krt14", "Sprr1a", "Sprr1b", "Evpl", "Dsp", "Ppl", "Klk11", "Spink5", "Klf4", "Klk6", "Klk7", "Klk8", "Klk10")

# cell_state_markers contains genes used to mark the cell cycle state of cells, in this case currently proliferative markers. 
cell_state_markers <- c("Mki67","Pcna")

# actin_markers contains all genes associated with the actin cytoskeleton. 
actin_markers <- c("Arhgdia","Camsap2", "Anxa1", "Rflnb", "Tmsb4x", "Arpc1b", "Sbsn","Dsg3", "Ahnak", "Cdh1", "Col3a1", "Tpt1", "Lgals7", "Rack1", "S100a11", "Eef1b2", "Ran", "Sprr1a", "Klf8", "Ptprf")

# plmn_markers has putative lamin bodies markers investigated. 
plmn_markers <- c("Ipo7", "Ran", "Snupn", "Matr3", "Nup153")

# SGPB_markers contains genes associated with condensates, primarly stress granules and P bodies.
SGPB_markers <- c("Ddx6", "Eif4e", "Nxf1", "Lsm14a", "Caprin1", "Csde1", "Pum1", "Zfp36")

# other_markers contains miscellaneous markers, notes below variable show reasoning. 
other_markers <- c("Snhg11", "Fabp5", "Slc25a4", "Lgals7", "Tacstd2", "Fosb", "Cd44", "Trpv4", "Trpm4" )

#Tr genes are calcium channels found specifically in UGL Matsui 2021
#kerato market genes not found
#("Klk5"))("Klk2"))("Klk3"))("Klk4"))("Klk9"))
# ("Crnn")) Cornulin  ("Sprr2a")) not found ("Sprr2b")) ("Sprr2c"))
# ("Sprr2d")) ("Sprr2e")) ("Sprr2f")) ("Sprr2g")) ("Sprr3")) ("Sprr4"))
# ("AABR07012329.1")) ("Lor")) ("Flg")) ("Rgpd1")) ("Syne4")) Dcp2, 

#dsg1, dsp - spinous, 
# spink5, granular

#Dsp, Ppl, Evpl

#combines all above lists into one superlist 'list_of_features', which is then parsed to later image functions. 
list_of_features <- c(kerato_marker_genes, cell_state_markers, actin_markers, plmn_markers, SGPB_markers, other_markers)
```


```{r}
# will make variable 'tidykerato', a form of object that can be easily parsed to data analysis, similar to tibble. 
# tidykerato <- tidyseurat::kerato
```

```{r}
# using pipes to push kerato QC data into boxplots. The three major QC covariates are plotted against frequency over the clusters. 

# Number of counts of RNA per barcode. 
kerato %>%
  tidyseurat::ggplot(aes(seurat_clusters, nCount_RNA, fill = seurat_clusters)) + # using ggplot2 aesthetics to change labels and add jitter. 
  geom_boxplot(outlier.shape = NA) +
  geom_jitter(width = 0.1) +
  xlab('Cluster') +
  ylab('RNA Read Count') +
  labs(fill = "Cluster") + theme(legend.position="none")

# Number of features per barcode. 
kerato %>%
  tidyseurat::ggplot(aes(seurat_clusters, nFeature_RNA, fill = seurat_clusters)) +
  geom_boxplot(outlier.shape = NA) + # using ggplot2 aesthetics to change labels and add jitter. 
  geom_jitter(width = 0.1) +
  xlab('Cluster') +
  ylab('RNA Feature Count') +
  labs(fill = "Cluster") + theme(legend.position="none")
  
# Percentage mitochondrial RNA content per barcode. 
kerato %>%
  tidyseurat::ggplot(aes(seurat_clusters, percent.mt, fill = seurat_clusters)) +
  geom_boxplot(outlier.shape = NA) + # using ggplot2 aesthetics to change labels and add jitter. 
  geom_jitter(width = 0.1) +
  xlab('Cluster') +
  ylab('Percentage mitochondrial RNA') +
  labs(fill = "Cluster") + theme(legend.position="none")
  
  
```

```{r}



VlnPlot(kerato, features = c("percent.mt")) + scale_x_discrete(name ="Cluster", limits=c("2","3","1", "0"), labels=c("Small", "Mid-stage","Late-stage", "Dead")) + ggtitle("Percentage mitochondrial RNA") + theme(axis.title.x = element_blank())

VlnPlot(kerato, features = c("nFeature_RNA")) + scale_x_discrete(name ="Cluster", limits=c("2","3","1", "0"), labels=c("Small", "Mid-stage","Late-stage", "Dead")) + ggtitle("Number of features") + theme(axis.title.x = element_blank())


VlnPlot(kerato, features = c("nCount_RNA")) + scale_x_discrete(name ="Cluster", limits=c("2","3","1", "0"), labels=c("Small", "Mid-stage","Late-stage", "Dead")) + ggtitle("Number of counts") + theme(axis.title.x = element_blank())

```

```{r}
# Chunk printing QC metrics to console, allows extraction and analysis of statistics. 

cat('counts')
summary(kerato$nCount_RNA)
cat('mito')
summary(kerato$percent.mt)
cat('features')
summary(kerato$nFeature_RNA)
```


```{r}
# Parse list_of_features to FeaturePlot, which gives heatmaps of the clusters showing a features expression. 

for (gene in list_of_features){

  p <- FeaturePlot(kerato, features = (gene))
  print(p)
}

# Use this line to see single feature plot, for ease. 
FeaturePlot(kerato, features = "Sbsn")
```
```{r}
#this will print all genes within a character vector's cluster graphs

# for (gene in actin_markers){
# 
#   p <- FeaturePlot(kerato, features = (gene))
#   print(p)
# }
```


```{r}
# Parse QC metrics to FeaturePlot, which gives heatmaps of the clusters showing a features expression. 

FeaturePlot(kerato, features = "percent.mt", label = TRUE)
FeaturePlot(kerato, features = "percent.mt")

FeaturePlot(kerato, features = "nFeature_RNA", label = TRUE)
FeaturePlot(kerato, features = "nFeature_RNA")

FeaturePlot(kerato, features = "nCount_RNA", label = TRUE)
FeaturePlot(kerato, features = "nCount_RNA")

#cluster graph showing labeled clusters
DimPlot(kerato, reduction = "umap", label = TRUE, pt.size = 0.5) 
```


```{r}
# Create list of marker genes for the clusters using filters. min.pct is the minimum percentage present. only.pos selects only positive markers for this.

markers_streamlined <-
  kerato %>%
  FindAllMarkers(only.pos = TRUE, min.pct = 0.25, thresh.use = 0.25) %>%
  group_by(cluster) %>% 
  top_n(10, avg_log2FC) # only take top ten genes.

# Plot heatmap
kerato %>%
  DoHeatmap(
    features = markers_streamlined$gene
    
  )

# changing text size with + theme(axis.text.y = element_text(size = 0.1)) doesn't seem to work, needs some graphical adjustments. 
```


```{r}
# Parse QC metrics to scatter plots using geom_point (ggplot2), adding smoothened line of best fit with stat_smooth, and pearson correlation coefficient with geom_cor. 

kerato %>%
  tidyseurat::ggplot(aes(x=Pseudotime, y=nCount_RNA)) + 
  geom_point() + 
  stat_smooth(method="lm", se=TRUE, colour = 'black', plot.cor = TRUE) + 
  geom_cor(method = "pearson")

kerato %>%
  tidyseurat::ggplot(aes(x=Pseudotime, y=percent.mt)) +   geom_point() + 
  stat_smooth(method="lm", se=TRUE, colour = 'black', plot.cor = TRUE) + 
  geom_cor(method = "pearson")

kerato %>%
  tidyseurat::ggplot(aes(x=Pseudotime, y=nFeature_RNA)) + 
  geom_point() + 
  stat_smooth(method="lm", se=TRUE, colour = 'black', plot.cor = TRUE) + 
  geom_cor(method = "pearson")


```


```{r}
# This chunk parses all feature genes to FeatureScatter, and adds a line of best fit with standard error region present. 

# for (gene in list_of_features){
#   #zero_scrub <- subset(x = kerato, subset =  (as.factor('Krt10') > 0))
#   # solution may be here: https://github.com/satijalab/seurat/issues/2619
#   
#   p <- FeatureScatter(kerato, feature1 = "Pseudotime", feature2 = (gene))
#   
#   print(p +
#           
#   theme(plot.title = element_text(hjust = 1.2, vjust = -2)) + # adjust pearsons coefficient to right hand side
#   stat_smooth(method="lm", se=TRUE, colour = 'black') + # regression line
#     
#   #labels
#   xlab('Pseudotime') + 
#   ylab(sprintf('%s Log2 Expression', gene)) +
#   labs(fill = "Cluster")) 
# }
```

```{r}

  #zero_scrub <- subset(x = kerato, subset =  (as.factor('Krt10') > 0))
  # solution may be here: https://github.com/satijalab/seurat/issues/2619
# obj_subset <- kerato[, GetAssayData(kerato[[assay]])[gene, ] > 1]
#actin_markers <- c("Arhgdia","Camsap2", "Anxa1", "Rflnb", "Tmsb4x", "Arpc1b", "Sbsn","Dsg3", "Ahnak", "Cdh1", "Col3a1", "Tpt1", "Lgals7", "Rack1", "S100a11", "Eef1b2", "Ran", "Sprr1a", "Klf8", "Ptprf") Cfl1, Ipo9, Xpo6, Tgm1

#                     set gene for line plot|
#                                           |
#                                           |

#experiment removing zero values from plot
# obj_subset <- subset(x = kerato, subset = Xpo6 > 0)
# 
# 
# p <- FeatureScatter(obj_subset, feature1 = "Pseudotime", feature2 = (gene))
#   
# print(p +
#           
# theme(plot.title = element_text(hjust = 1.2, vjust = -2)) + # adjust pearsons coefficient to right hand side
# stat_smooth(method="lm", se=TRUE, colour = 'black') + # regression line
#     
#   #labels
# xlab('Pseudotime') + 
# ylab(sprintf('%s Log2 Expression', gene)) +
# labs(fill = "Cluster")) 

```

```{r}
#chunk plotting all pseudotime line graphs for genes in a character vector

# for (gene in actin_markers){
#   
#   p <- FeatureScatter(kerato, feature1 = "Pseudotime", feature2 = (gene))
#   
#   print(p +
#           
#   theme(plot.title = element_text(hjust = 1.2, vjust = -2)) + # adjust pearsons coefficient to right hand side
#   stat_smooth(method="lm", se=TRUE, colour = 'black') + # regression line
#     
#   #labels
#   xlab('Pseudotime') + 
#   ylab(sprintf('%s Log2 Expression', gene)) +
#   labs(fill = "Cluster")) 
# }
```


```{r}
# Similar to chunk above, investigating single genes for ease of use. 

pseudotime_scatter_gene <- 'Ctsa'
#"Ddx6", "Eif4e"

#b, l, d, s, h, c, k, e, g, z, j, f, r, m, 7, a, q

FeatureScatter(kerato, feature1 = "Pseudotime", feature2 = (pseudotime_scatter_gene)) +
  theme(plot.title = element_text(hjust = 1.2, vjust = -2)) + # adjust pearsons coefficient to right hand side
  stat_smooth(method="lm", se=TRUE, colour = 'black') + # regression line
    
  #labels
  xlab('Pseudotime') + 
  ylab(sprintf('%s Log2 Expression', pseudotime_scatter_gene)) +
  labs(fill = "Cluster") 

FeaturePlot(kerato, features = (pseudotime_scatter_gene))

```



